### ISSUE TITLE
DAP 6.2.1 cluster does not start successfully  [Potential issue]

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/kubernetes-conjur-deploy#80] opened 2019-11-05 13:47 UTC
We've gotten a number of internal reports that this deploy works fine with the DAP `6.2.0` version but fails with the `6.2.1` version (the latest release).  Examples include:
- Shahar: https://conjurhq.slack.com/archives/CCMKTQMH6/p1572880097022400?thread_ts=1572857997.020200&cid=CCMKTQMH6
- Geri: https://github.com/cyberark/kubernetes-conjur-deploy/issues/76
- John (Decomposed follower testing)

I'd like us to investigate to better understand the issue. Please:
1. Try to replicate the problem (deploy a `6.2.1` cluster to our OCP environment, and validate it's functioning as intended)
2. Assuming we can replicate the problem, try to resolve the issue.

**Comment by sgnn7** [comment] 2019-11-05 16:29
Looks to be caused by the follower trying to send audit data to master over 5433 (pg) rather than 1999 (syslog), causing the health check to fail and the service to be non-routable. Looking into this to find the root cause.

**Comment by sgnn7** [comment] 2019-11-07 17:28
Second PR that got merged today should in theory get things rolling here. Build is pending:
https://jenkins.conjur.net/blue/organizations/jenkins/conjurdemos--kubernetes-conjur-demo/detail/master/263/pipeline/

**Comment by sgnn7** [comment] 2019-11-07 17:48
Completed: https://jenkins.conjur.net/job/conjurdemos--kubernetes-conjur-demo/job/master/263/

**Closed** 2019-11-07 17:49 UTC
Labels: component/openshift, kind/bug, severity/high
